:default_env:
  :this:
    :env:
      :val: 'default'
  :that:
    :nested_env:
      :default_env:
        :nested_val: 'default_nested_val'
        :other_nested_val: 'other_default_nested_val'
      :test:
        :nested_val: 'nested_test'
      :production:
        :nested_val: 'nested_production'

:production:
  :that:
    :nested_env:
      :thingy: 'blah'

:test:
  :that:
    :nested_env:
      :thingy: 'bloh'
  :this:
    :env:
      :val: 'test'
